### ISSUE TITLE
Hardcoded data advertising

### ISSUE THREAD

**Issue by TraitorablePL** [TraitorablePL/BLE_BeaconSensor#1]
### TASKS:
- [x] Custom Service and characteristics for data aqusition 
- [x] Notification of sine float data
- [x] Use of pre-initiated look-up table for sine readings
- [x] Notification of counter integer data
- [x] Proper descriptors for characteristics
- [x] Handling of notification request

###  FIXES:
- [x] After reconnect device doesn't receive notifications until notifications from previous connection are turned off
- [x] Changed project file structure
- [x] Flash and RAM Memory adjustments

**Comment by TraitorablePL** [comment]
Hardcoded advertising done. Further development will be done in separate issue after app will be moved to target beacon board with needed sensors.
