### ISSUE TITLE
Power consumption optimization

### ISSUE THREAD

**Issue by TraitorablePL** [TraitorablePL/BLE_BeaconSensor#2]
### TASKS:
- [ ] Adjustment of advertising interval
- [ ] Adjustment of connection interval
- [ ] Usage of low energy modes
