### ISSUE TITLE
Client application for aquisition of server data 

### ISSUE THREAD

**Issue by TraitorablePL** [TraitorablePL/BLE_BeaconSensor#3]
### TASKS:

- [ ] Connection with server board
- [ ] Service and characteristics discovery
- [ ] Notification value readings
