### ISSUE TITLE
Client application for aquisition of server data nRF52840 (Nordic Dongle)

### ISSUE THREAD

**Issue by TraitorablePL** [TraitorablePL/BLE_BeaconSensor#4]
### TASKS:

- [x] Setup of USB CDC ACM example on Dongle
- [x] Setup of HeartRate Sensor Client example on Dongle
- [x] Merge of two above examples into one App (Client App)
- [x] Client App functionality test with Heart Rate Server
- [x] Remove of unnecessary bonding and security features from Client App
- [x] Client App adjustments to perform connection with ACQ Beacon
- [x] Setup of notifications from ACQ Beacon
- [x] Functionality tests

**Comment by TraitorablePL** [comment]
Part for Nordic Dongle client setup can be closed. Updates related with final sensors readings will be part of project finalizing issue.
